# Generated by Django 3.0.6 on 2020-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('mobile', models.IntegerField(default=0)),
                ('subject', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
